volumes:
  postgres_volume_auth_service:

services:
  pg-auth:
    image: postgres:16-alpine3.20
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT_OUTER}:${PG_PORT_INNER}"
    volumes:
      - postgres_volume_auth_service:/var/lib/postgresql/data
       
  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile

    restart: on-failure
    environment:
        DB_HOST: pg-auth

  auth-service:
    build: .
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
    restart: unless-stopped
    depends_on:
      - pg-auth
      - migrator
